//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.Service.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int adsId { get; set; }
        public string adsBody { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
